### ISSUE TITLE
mac M1.Installation error

### ISSUE THREAD

**Issue by ghost** [wg/wrk#456] opened 2021-03-18 02:57 UTC
`brew install wrk`

```
Error: wrk: no bottle available!
You can try to install from source with:
  brew install --build-from-source wrk
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```

`brew install --build-from-source wrk`

```
crypto/aes/aes-x86_64.s:1741:9: error: unexpected token in argument list
 movq 32(%rsi),%rbp
        ^
crypto/aes/aes-x86_64.s:1742:9: error: unexpected token in argument list
 movq 40(%rsi),%rbx
        ^
crypto/aes/aes-x86_64.s:1743:9: error: unexpected token in argument list
 leaq 48(%rsi),%rsp
        ^
crypto/aes/aes-x86_64.s:1745:2: error: unrecognized instruction mnemonic
 popfq
 ^
make[2]: *** [crypto/aes/aes-x86_64.o] Error 1
make[1]: *** [all] Error 2
make: *** [obj/lib/libssl.a] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!
```

`brew config`

```
HOMEBREW_VERSION: 3.0.7-11-g53f34af
ORIGIN: https://github.com/Homebrew/brew
HEAD: 53f34af1c53c5716a77255d3227a5ba2cdc58ea9
Last commit: 21 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3c81322a5a405ee2e5eb79ab624ea7297aed7afb
Core tap last commit: 19 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-arm64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
Rosetta 2: false
```

**Comment by davidepedranz** [comment] 2021-04-01 10:13
If it helps, I managed to compile `wrt` on an M1 chip as follows by cloning the repository, replacing the first 2 lines of the `Makefile` with the following block, and running `make`:

```Makefile
CFLAGS  := -O2 -D_REENTRANT -I/opt/homebrew/opt/openssl/include
LIBS    := -lpthread -lm -lcrypto -lssl -L/opt/homebrew/opt/openssl/lib
```

This assumes that you already installed `openssl` with `brew install openssl` ;-)

**Comment by lzskyline** [comment] 2021-04-25 02:08
@davidepedranz works for me :)

**Comment by leonstafford** [comment] 2021-05-20 15:07
If anyone's afraid to ask and doesn't know, after following [David's build instructions in previous comment](https://github.com/wg/wrk/issues/456#issuecomment-811806488), this should generate a `wrk` executable file in the same directory. You can run this by typing `./wrk` from within this directory. If you'd like to be able to run it from anywhere, copy it to somewhere on your system's `PATH`, where it looks for programs. ie `sudo cp wrk /usr/local/bin`.

**Comment by mukesh-panigrahi-searce** [comment] 2021-08-26 11:58
Getting below error while make build, any idea what can be done? 

Building OpenSSL...
"glob" is not exported by the File::Glob module
Can't continue after import errors at ./Configure line 17.
BEGIN failed--compilation aborted at ./Configure line 17.
make: *** [obj/lib/libssl.a] Error 255

Openssl is installed as well.
$ openssl version -a
LibreSSL 2.8.3
built on: date not available
platform: information not available
options:  bn(64,64) rc4(ptr,int) des(idx,cisc,16,int) blowfish(idx)

**Comment by mukesh-panigrahi-searce** [comment] 2021-08-27 00:18
the issue is fixed now. I was using release 4.1.0 where I got the above error. After doing a fresh git clone from master wrk build was successful.

./wrk --version
wrk 4.1.0-8-ga211dd5 [kqueue] Copyright (C) 2012 Will Glozer

**Comment by dalisoft** [comment] 2021-09-17 09:16
On macOS Catalina, Big Sur and Monterey at Intel and M1 machines this command should work `brew install wrk --build-from-source --HEAD`

**Comment by pantuza** [comment] 2021-11-05 01:24
> On macOS Catalina, Big Sur and Monterey at Intel and M1 machines this command should work `brew install wrk --build-from-source --HEAD`

The command described by @dalisoft above ⬆️ worked for me by adding the prefix `arch -arm64` on a M1 running Mac OS Big Sur version 11.6 . 

Thus, the complete command was:
```bash
arch -arm64 brew install wrk --build-from-source --HEAD
```

**Comment by wg** [comment] 2021-12-13 05:14
I've tagged wrk 4.2.0 which includes the relevant fixes for arm64 and hopefully should resolve any homebrew installation issues. However homebrew packaging is a 3rd party effort unrelated to this repository.

**Closed as completed by wg** 2021-12-13 05:14 UTC
